ALTER TABLE products
    ALTER COLUMN value SET DATA TYPE INTEGER;

ALTER TABLE raw_materials
    ALTER COLUMN id SET DATA TYPE VARCHAR(255),
    ALTER COLUMN stock_quantity SET DATA TYPE INTEGER;

ALTER TABLE product_materials
    ALTER COLUMN product_id SET DATA TYPE VARCHAR(255),
    ALTER COLUMN raw_material_id SET DATA TYPE VARCHAR(255),
    ALTER COLUMN required_quantity SET DATA TYPE INTEGER;
